### PR TITLE
Fix validation of an external resource id

### PR DESCRIPTION
**Pull request by hvelarde**

### CODE REVIEW

**Comment by hvelarde** [comment]
CC @mauritsvanrees @plone/framework-team

**Comment by jensens** [comment]
@hvelarde looks like Python 2.6 does not like ``assertNotIn``:
http://jenkins.plone.org/job/plone-4.3-python-2.6/1464/testReport/junit/Products.ResourceRegistries.tests.testJSRegistry/TestJSScriptRenaming/testRenamingExternal/

Can you fix this today? Otherwise I'd revert.

**Comment by hvelarde** [comment]
sorry about that; fixed in https://github.com/plone/Products.ResourceRegistries/commit/3a7949e2050d8f6c7c567235d31c115ce05f8686

**Comment by jensens** [comment]
thanks!

**Pull request merged**
